"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$os\
$username\
[$hostname$localip](bg:color_orange)\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_commit\
$git_metrics\
$git_status\
$git_state\
[](fg:color_aqua bg:color_blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$ruby\
[](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
$aws\
$gcloud\
$azure\
$package\
$terraform\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$fill\
$line_break\
$fill\
$memory_usage\
$jobs\
$cmd_duration\
$line_break$shell$shlvl$status$character$sudo"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[cmd_duration]
min_time = 1
format = ' [$duration](bold color_yellow)'
show_milliseconds = true
show_notifications = true
min_time_to_notify = 15_000

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user]($style)'

[shell]
unknown_indicator = '?'
style = 'color_green bold'
disabled = false

[shlvl]
disabled = false
style = 'bold color_green'
format = '[ $shlvl ]($style)'
threshold = 2

[status]
symbol = ' '
sigint_symbol = ' '
not_found_symbol = '[](color_yellow) '
format = '[$symbol]($style) '
map_symbol = true
disabled = false

[sudo]
style = 'bold color_green'
symbol = '󰌿 '
disabled = false

[character]
success_symbol = '[➜](bold color_green)'
#error_symbol = '[✗](bold color_red)'
error_symbol = ''

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[fill]
symbol = '.'
style = 'bold dimmed black'

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_commit]
commit_hash_length = 4
style = "bg:color_aqua"
format = '[\($hash$tag\)]($style)'
tag_symbol = ' 🏷  '
tag_max_candidates = 20
only_detached = false
tag_disabled = false

[git_metrics]
added_style = 'bold color_green bg:color_aqua'
deleted_style = 'bold color_red bg:color_aqua'
format = '[[+$added]($added_style)/[-$deleted]($deleted_style) ](bg:color_aqua)'
disabled = false

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[hostname]
ssh_only = false
format = '[[$ssh_symbol](bold color_blue bg:color_orange) on [$hostname](bold color_blue bg:color_orange)](bg:color_orange)'
trim_at = ''
disabled = false

[jobs]
symbol = '  '
number_threshold = 0
symbol_threshold = 0
style = 'bold color_blue'
format = '[ ∑$number$symbol]($style) '

[localip]
ssh_only = false
style = 'bg:color_orange bold color_green'
format = '@[$localipv4]($style) '
disabled = false

[memory_usage]
disabled = false
threshold = -1
symbol = ''
style = 'bold color_green'
format = ' $symbol [ ram: ${ram} ${ram_pct}( | swap: ${swap} ${swap_pct})]($style) '


[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[package]
format = '[🎁 $version](208 bold) '

[terraform]
format = '[🏎💨 $workspace]($style) '

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false